apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
    component: db
    instance: postgres
    name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      component: db
      instance: postgres
      name: postgres
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: postgres
        component: db
        instance: postgres
        name: postgres
    spec:
      containers:
      - name: postgres-container
        image: dockerhub-dockerio.icellmobilsoft.hu/postgres:14.1
        env:
        - name: POSTGRES_USER
          value: "core_exemption_service"
        - name: POSTGRES_PASSWORD
          value: "mlffTitkosPassword123"
        - name: POSTGRES_DB
          value: "coredb"
        imagePullPolicy: Never
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
    component: db
    instance: postgres
    name: postgres
spec:
  type: NodePort
  selector:
    app: postgres
    component: db
    instance: postgres
    name: postgres
  ports:
  - name: business
    protocol: TCP
    port: 5432
    targetPort: 5432
    nodePort: 32004
