apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-b-deployment
  labels:
    app: restB
    component: backend
    instance: restB
    name: restB
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restB
      component: backend
      instance: restB
      name: restB
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: restB
        component: backend
        instance: restB
        name: restB
    spec:
      containers:
      - name: rest-b-container
        image: sample-service-b:0.0.1
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "2"
        imagePullPolicy: Never
        env:
        - name: POSTGRESQL_DS_MAX_POOL_SIZE
          value: "5"
        ports:
        - containerPort: 9990
        - containerPort: 8080
        # system probes
        startupProbe:
          httpGet:
            path: /health/started
            port: 9990
          initialDelaySeconds: 15
          periodSeconds: 8
          failureThreshold: 50
        livenessProbe:
          httpGet:
            path: /health/live
            port: 9990
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 100
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 9990
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: rest-b-service
  labels:
    app: restB
    component: backend
    instance: restB
    name: restB
spec:
  type: NodePort
  selector:
    app: restB
    component: backend
    instance: restB
    name: restB
  ports:
  - name: management
    protocol: TCP
    port: 9990
    targetPort: 9990
    nodePort: 31001
  - name: business
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32001
