version: "3.8"

# futtatas
# docker-compose -f <PROJECT_PATH>/backend-sampler/etc/docker-compose/docker-compose.local.demoA.yml up --build --force-recreate
services:
  sample-service-a:
    container_name: sample-rest-service-local-b
    build:
      context: ../../
      dockerfile: etc/docker-compose/release.dockerfile
      args:
        WILDFLY_BASE_IMAGE: 'dockerhub.icellmobilsoft.hu/wildfly-ms/postgresql-jdbc:0.6.0'
        WILDFLY_CLI_PATH: etc/docker-compose/jboss-cli/*.*
        PROPERTIES_FILE: 'etc/docker-compose/wildfly/wf.properties'
    image: sample-service-b:0.0.1
    volumes:
      - './wildfly/wf.properties:/appconfig/app.properties'
    ports:
      - '8081:8080'
      - '9991:9990'
      - '8788:8787'
    environment:
      OPENTRACING_JAEGER_AGENT_HOST: jaeger
      JAEGER_SERVICE_NAME: demoB
      POSTGRESQL_DS_MAX_POOL_SIZE: 10
      OPENTRACING_JAEGER_PROPAGATION: JAEGER
#      MP_CONFIG_PROFILE: local
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
networks: 
  default: 
    external: 
      name: bs-local-network
